"""initial schema

Revision ID: 7b407f21957a
Revises: 
Create Date: 2026-08-15 11:27:38.644016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b407f21957a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_name', sa.String(length=120), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=40), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=40), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_type'), ['actor_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_id'), ['resource_id'], unique=False)

    op.create_table('depots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('depot_code', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=80), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('depot_code')
    )
    op.create_table('model_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('triggered_by', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('training_rows', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=40), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=40), nullable=True),
    sa.Column('metric_value', sa.Float(), nullable=True),
    sa.Column('higher_is_better', sa.Boolean(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('dataset_rows', sa.Integer(), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name', 'version', name='uq_modelversion_name_version')
    )
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_versions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_versions_model_name'), ['model_name'], unique=False)

    op.create_table('otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=120), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otps_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_otps_identifier'), ['identifier'], unique=False)

    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_code', sa.String(length=20), nullable=True),
    sa.Column('vehicle_no', sa.String(length=30), nullable=False),
    sa.Column('vehicle_type', sa.String(length=40), nullable=True),
    sa.Column('fuel_type', sa.String(length=30), nullable=True),
    sa.Column('mileage', sa.Float(), nullable=True),
    sa.Column('capacity_kg', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('health_score', sa.Float(), nullable=True),
    sa.Column('insurance_expiry', sa.Date(), nullable=True),
    sa.Column('permit_expiry', sa.Date(), nullable=True),
    sa.Column('pollution_cert_expiry', sa.Date(), nullable=True),
    sa.Column('depot_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('total_km', sa.Float(), nullable=True),
    sa.Column('last_service_date', sa.Date(), nullable=True),
    sa.Column('service_count', sa.Integer(), nullable=True),
    sa.Column('breakdown_count', sa.Integer(), nullable=True),
    sa.Column('maintenance_cost_total', sa.Float(), nullable=True),
    sa.CheckConstraint('capacity_kg IS NULL OR capacity_kg > 0', name='ck_vehicle_capacity_positive'),
    sa.CheckConstraint('health_score IS NULL OR (health_score >= 0 AND health_score <= 100)', name='ck_vehicle_health_score_range'),
    sa.CheckConstraint('mileage IS NULL OR mileage > 0', name='ck_vehicle_mileage_positive'),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_code'),
    sa.UniqueConstraint('vehicle_no')
    )
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicles_depot_id'), ['depot_id'], unique=False)

    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_code', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('dob', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('license_no', sa.String(length=60), nullable=True),
    sa.Column('experience_years', sa.Integer(), nullable=True),
    sa.Column('emergency_contact', sa.String(length=20), nullable=True),
    sa.Column('license_doc_path', sa.String(length=255), nullable=True),
    sa.Column('profile_photo_path', sa.String(length=255), nullable=True),
    sa.Column('address_proof_path', sa.String(length=255), nullable=True),
    sa.Column('eco_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('rejection_reason', sa.String(length=255), nullable=True),
    sa.Column('assigned_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('depot_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_vehicle_id'], ['vehicles.id'], ),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_code'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_drivers_assigned_vehicle_id'), ['assigned_vehicle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_drivers_depot_id'), ['depot_id'], unique=False)

    op.create_table('service_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('service_date', sa.Date(), nullable=False),
    sa.Column('service_type', sa.String(length=60), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('was_breakdown', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('cost >= 0', name='ck_servicerecord_cost_non_negative'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_records_vehicle_id'), ['vehicle_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audience', sa.String(length=20), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_driver_id'), ['driver_id'], unique=False)

    op.create_table('saved_tips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_code', sa.String(length=20), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=150), nullable=True),
    sa.Column('destination', sa.String(length=150), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('load_kg', sa.Float(), nullable=True),
    sa.Column('purpose', sa.String(length=150), nullable=True),
    sa.Column('preferred_route', sa.String(length=50), nullable=True),
    sa.Column('route_chosen', sa.String(length=50), nullable=True),
    sa.Column('weather_condition', sa.String(length=50), nullable=True),
    sa.Column('traffic_condition', sa.String(length=50), nullable=True),
    sa.Column('predicted_fuel_l', sa.Float(), nullable=True),
    sa.Column('predicted_co2_kg', sa.Float(), nullable=True),
    sa.Column('predicted_cost', sa.Float(), nullable=True),
    sa.Column('predicted_eco_score', sa.Float(), nullable=True),
    sa.Column('maintenance_risk', sa.String(length=20), nullable=True),
    sa.Column('recommended_route', sa.String(length=50), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('origin_lat', sa.Float(), nullable=True),
    sa.Column('origin_lng', sa.Float(), nullable=True),
    sa.Column('dest_lat', sa.Float(), nullable=True),
    sa.Column('dest_lng', sa.Float(), nullable=True),
    sa.Column('estimated_duration_min', sa.Float(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=True),
    sa.Column('route_polyline', sa.Text(), nullable=True),
    sa.Column('deviation_flagged', sa.Boolean(), nullable=True),
    sa.Column('actual_fuel_l', sa.Float(), nullable=True),
    sa.Column('actual_co2_kg', sa.Float(), nullable=True),
    sa.Column('actual_cost', sa.Float(), nullable=True),
    sa.Column('actual_fuel_price', sa.Float(), nullable=True),
    sa.Column('co2_methodology_version', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('Planned','Ongoing','Completed','Cancelled')", name='ck_trip_status_valid'),
    sa.CheckConstraint('actual_fuel_l IS NULL OR actual_fuel_l >= 0', name='ck_trip_actual_fuel_non_negative'),
    sa.CheckConstraint('actual_fuel_price IS NULL OR actual_fuel_price >= 0', name='ck_trip_actual_fuel_price_non_negative'),
    sa.CheckConstraint('distance_km IS NULL OR distance_km > 0', name='ck_trip_distance_positive'),
    sa.CheckConstraint('load_kg IS NULL OR load_kg >= 0', name='ck_trip_load_non_negative'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_code')
    )
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trips_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trips_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_trips_vehicle_id'), ['vehicle_id'], unique=False)
        batch_op.create_index('uq_trip_one_ongoing_per_driver', ['driver_id'], unique=True, sqlite_where=sa.text("status = 'Ongoing'"), postgresql_where=sa.text("status = 'Ongoing'"))

    op.create_table('route_deviations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('deviation_m', sa.Float(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("status IN ('Active','Resolved')", name='ck_routedev_status_valid'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('route_deviations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_route_deviations_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_route_deviations_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_route_deviations_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_route_deviations_trip_id'), ['trip_id'], unique=False)

    op.create_table('trip_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('speed_kmph', sa.Float(), nullable=True),
    sa.Column('heading', sa.Float(), nullable=True),
    sa.Column('accuracy_m', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('lat >= -90 AND lat <= 90', name='ck_triploc_lat_range'),
    sa.CheckConstraint('lng >= -180 AND lng <= 180', name='ck_triploc_lng_range'),
    sa.CheckConstraint('speed_kmph IS NULL OR speed_kmph >= 0', name='ck_triploc_speed_non_negative'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trip_locations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_locations_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trip_locations_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_trip_locations_trip_id'), ['trip_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_locations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_locations_trip_id'))
        batch_op.drop_index(batch_op.f('ix_trip_locations_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_trip_locations_driver_id'))

    op.drop_table('trip_locations')
    with op.batch_alter_table('route_deviations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_route_deviations_trip_id'))
        batch_op.drop_index(batch_op.f('ix_route_deviations_status'))
        batch_op.drop_index(batch_op.f('ix_route_deviations_driver_id'))
        batch_op.drop_index(batch_op.f('ix_route_deviations_detected_at'))

    op.drop_table('route_deviations')
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_index('uq_trip_one_ongoing_per_driver', sqlite_where=sa.text("status = 'Ongoing'"), postgresql_where=sa.text("status = 'Ongoing'"))
        batch_op.drop_index(batch_op.f('ix_trips_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_trips_status'))
        batch_op.drop_index(batch_op.f('ix_trips_driver_id'))

    op.drop_table('trips')
    op.drop_table('saved_tips')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_driver_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('service_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_records_vehicle_id'))

    op.drop_table('service_records')
    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_drivers_depot_id'))
        batch_op.drop_index(batch_op.f('ix_drivers_assigned_vehicle_id'))

    op.drop_table('drivers')
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicles_depot_id'))

    op.drop_table('vehicles')
    op.drop_table('settings')
    with op.batch_alter_table('otps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otps_identifier'))
        batch_op.drop_index(batch_op.f('ix_otps_created_at'))

    op.drop_table('otps')
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_versions_model_name'))
        batch_op.drop_index(batch_op.f('ix_model_versions_is_active'))

    op.drop_table('model_versions')
    op.drop_table('model_runs')
    op.drop_table('depots')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    op.drop_table('admins')
    # ### end Alembic commands ###
