"""add trip feedback table

Revision ID: 9c0c08364078
Revises: b78a8f7d0b24
Create Date: 2026-08-20 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c0c08364078'
down_revision = 'b78a8f7d0b24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trip_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('overall_rating', sa.Integer(), nullable=False),
    sa.Column('navigation_rating', sa.Integer(), nullable=False),
    sa.Column('eco_route_rating', sa.Integer(), nullable=False),
    sa.Column('experience', sa.String(length=20), nullable=False),
    sa.Column('comments', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('overall_rating >= 1 AND overall_rating <= 5', name='ck_tripfeedback_overall_rating_range'),
    sa.CheckConstraint('navigation_rating >= 1 AND navigation_rating <= 5', name='ck_tripfeedback_navigation_rating_range'),
    sa.CheckConstraint('eco_route_rating >= 1 AND eco_route_rating <= 5', name='ck_tripfeedback_eco_route_rating_range'),
    sa.CheckConstraint("experience IN ('Excellent','Good','Average','Poor','Very Poor')", name='ck_tripfeedback_experience_valid'),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', name='uq_tripfeedback_trip_id')
    )
    with op.batch_alter_table('trip_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trip_feedback_driver_id'), ['driver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trip_feedback_trip_id'), ['trip_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trip_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trip_feedback_trip_id'))
        batch_op.drop_index(batch_op.f('ix_trip_feedback_driver_id'))

    op.drop_table('trip_feedback')
    # ### end Alembic commands ###
