"""add account lockout fields and carbon methodology table

Revision ID: b78a8f7d0b24
Revises: 2d0604717a0a
Create Date: 2026-08-15 17:20:03.079884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b78a8f7d0b24'
down_revision = '2d0604717a0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carbon_methodologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_label', sa.String(length=20), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('emission_factors', sa.Text(), nullable=False),
    sa.Column('price_per_unit', sa.Text(), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_label')
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))

    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('locked_until', sa.DateTime(), nullable=True))

    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('methodology_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_trips_methodology_id'), ['methodology_id'], unique=False)
        batch_op.create_foreign_key('fk_trips_methodology_id_carbon_methodologies', 'carbon_methodologies', ['methodology_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_constraint('fk_trips_methodology_id_carbon_methodologies', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_trips_methodology_id'))
        batch_op.drop_column('methodology_id')

    with op.batch_alter_table('drivers', schema=None) as batch_op:
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_attempts')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('locked_until')
        batch_op.drop_column('failed_login_attempts')

    op.drop_table('carbon_methodologies')
    # ### end Alembic commands ###
